@host = http://localhost:3000
@api = /api/geotags



### GET start page //working
GET {{host}}


### GET with latitude, longitude, searchterm present (Koordinaten IWI) //working

GET {{host}}{{api}}
Content-Type: application/json

{
    "latitude" : 49.01379,
    "longitude" : 8.390071,
    "searchterm" : "#campus"
}


### GET with latitude, longitude only present

GET {{host}}{{api}}
Content-Type: application/json

//--- in latitude und longitude muss nur irgendeine Zahl stehen, welche ist dabei egal ---//
//--- das ist nicht so dolle, I guess ---//
{
//--- Koordinaten IWI ---//
  //  "latitude" : 49.01379,
   // "longitude" : 8.390071
//--- Koordinaten HS Mannheim ---//
   "latitude" : 49.47009,
   "longitude" : 8.48240
}


### POST new GeoTag (nach jedem Post sollte sich die ID um 1 erhöhen) //working

POST {{host}}{{api}}
Content-Type: application/json

{
    "latitude" : 49.01486,
    "longitude" : 8.39407,
    "name" : "Mensa",
    "hashtag" : "#campus"
}


### GET GeoTag by ID (ID 1 = IWI) //working

GET {{host}}{{api}}/1


### PUT replace existing GeoTag //working

PUT {{host}}{{api}}/1
Content-Type: application/json

{
    "latitude" : 49.01379,
    "longitude" : 8.390071,
    "name" : "Replaced",
    "hashtag" : "#replaced"
}


### DELETE existing GeoTag (ID 0 = Castle) //working

DELETE {{host}}{{api}}/0
