@host = http://localhost:3000
@api = /api/geotags



### GET start page //working
GET {{host}}


### GET with latitude, longitude, searchterm present //working

GET {{host}}{{api}}
Content-Type: application/json

{
//--- Koordinaten der IWI (beliebige Zahlen reichen) ---//
    "latitude" : 49.01379,
    "longitude" : 8.390071,
    "searchterm" : "#campus"
}


### GET with latitude, longitude only present (nicht mehr nach searchterm filtern)

GET {{host}}{{api}}
Content-Type: application/json

{
//--- Koordinaten IWI (beliebige Zahlen reichen) ---//
    "latitude" : 49.01379,
    "longitude" : 8.390071
}


### POST new GeoTag (nach jedem Post sollte sich die ID um 1 erhöhen) //working

POST {{host}}{{api}}
Content-Type: application/json

{
    "name" : "NewGeoTag",
    "hashtag" : "#newtag"
}


### GET GeoTag by ID (ID 1 = IWI) //working

GET {{host}}{{api}}/1


### PUT replace existing GeoTag //working

PUT {{host}}{{api}}/1
Content-Type: application/json

{
    "name" : "Replaced",
    "hashtag" : "#replace"
}


### DELETE existing GeoTag (ID 0 = Castle) //working

DELETE {{host}}{{api}}/0
